spring:
  application:
    name: chat-service
  datasource:
    url: jdbc:h2:mem:the-commerce;NON_KEYWORDS=USER
    username: sa
    password:
    driver-class-name: org.h2.Driver
  h2:
    console:
      enabled: true
  jpa:
    database-platform: H2
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: create-drop
    open-in-view: false

  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: chat-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

kafka:
  topic:
    chat: chat-message


server.port: 8080


